apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sazurev1ingresshttpsonly
spec:
  crd:
    spec:
      names:
        kind: K8sAzureV1IngressHttpsOnly
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sazurev1ingresshttpsonly
        violation[{"msg": msg}] {
          input.review.kind.kind == "Ingress"
          re_match("^(extensions|networking.k8s.io)$", input.review.kind.group)
          violate_allow_http[{"msg": msg}]
        }

        # Nginx Ingress Controller Violation
        violate_allow_http[{"msg": msg}] {
          ingress := input.review.object
          not complaint_nginx_cases(ingress)
          msg := sprintf("Ingress should have annotation nginx.org/ssl-services. tls configuration and annotation nginx.org/ssl-services=tea-svc are required)
        }
        complaint_nginx_cases(ingress) {
          ingress.metadata.annotations["nginx.org/ssl-services"] == "coffee-svc2"
          count(ingress.spec.tls) > 0
        }
