apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureV1RequiredAnnotations
metadata:
  name: ns-must-have-annotation
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Ingress"]
  parameters:
    annotations: : {{ .Values.annotations }}
